.travis.yml
snoop/data/magic.py

Fix travis

---

snoop/data/digests.py
snoop/data/models.py
snoop/data/urls.py
snoop/data/utils.py
snoop/data/views.py
snoop/defaultsettings.py

* show full path to a file
* click-browse through directories
* paginate the api document feed
* download original files

Api features

---

snoop/data/models.py

With this patch, walk doesn't overwrite existing blobs in the blob storage.

only write new blobs to the storage

---

snoop/data/management/commands/runworkers.py

`./manage.py runworkers -n 24`

parametrize number of workers

---

snoop/data/models.py
snoop/data/tasks.py

Funnel all updates to task state through an "update" function which makes sure that all 4 state fields are updated.

Task state

---

Dockerfile

closes https://github.com/hoover/snoop2/issues/52
```
$ docker run --rm -t snoop2 which file                                                                                                         
/opt/hoover/snoop/magic-definitions/file/bin/file
```

Docker compile file

---

snoop/data/ocr.py
testsuite/test_ocr.py

ability to import ocr text files

---

snoop/data/admin.py
snoop/data/digests.py
snoop/data/filesystem.py
testsuite/test_digest.py

Fixes https://github.com/hoover/snoop2/issues/39

Handle broken dependencies

---

requirements.in
requirements.txt
snoop/data/analyzers/email.py
snoop/data/analyzers/tika.py
snoop/data/digests.py
snoop/data/utils.py
testsuite/test_emails.py
testsuite/test_tika.py

closes https://github.com/hoover/snoop2/issues/45

Date fields

---

.travis.yml
Dockerfile

closes https://github.com/hoover/snoop2/issues/64

Build latest libpst using Docker

---

snoop/data/ocr.py

Fixes https://github.com/hoover/snoop2/issues/70

split ocr.walk_source into recursive tasks

---

snoop/data/tasks.py

I need to be able to retry an existing task if it was already created, e.g. [here](https://gist.github.com/mgax/5f6ff8b50c85462ba1e0dd3ee970189d#file-retry-mbox-py-L14) in a script to re-process mbox files.

Retry shaorma if it was already run

---

snoop/data/analyzers/email.py

Reindexing of documents is needed

fix(encoding): Detect the right encoding for emails

---

requirements.txt
snoop/data/collections.py
snoop/data/indexing.py
snoop/data/management/commands/runworkers.py
snoop/data/management/commands/updatename.py

- do not remove the collection record from the database on collection removal (the whole database is removed anyway)
- set the collection index name properly in elasticsearch (lowercase) on collection creation
- fix hanging of the indexing tasks

fix collection removal; fix index name; fix tasks hang

---

testsuite/test_walk.py

Part of https://github.com/CRJI/EIC/issues/110

Add test for walking across the same archive twice.

---

snoop/data/management/commands/runworkers.py
snoop/data/tasks.py
snoop/defaultsettings.py

periodically runs a walk task on the filesystem to sync the files in the collection with hoover

Auto-sync feature for collections

---

snoop/data/management/commands/runworkers.py

If we want concurrency, we can use multiple workers: https://github.com/liquidinvestigations/node/blob/master/templates/collection.nomad#L113-L114

Run a single celery worker

---

.travis.yml
Dockerfile
snoop/defaultsettings.py
testsuite/docker-compose.override.travis-snoop2.yml

Error out the `settings` file if the database is not configured.

Fix postgresql config

---

snoop/data/digests.py
snoop/data/views.py

* Trim text if it's more than 1 million chars
* Aviod loading digest when downloading raw file
* Fix random typo

Preview large files

---

snoop/data/management/commands/printstats.py

Convenient management command, copied from quick and dirty script on server, for posterity

Print task stats

---

snoop/data/management/commands/workisdone.py

Tested manually, works as a charm.

Check if work is done

---

snoop/data/collections.py
snoop/data/indexing.py
snoop/data/management/commands/purge.py

fixes liquidinvestigations/hoover-snoop2#321

add "purge" management command

---

Dockerfile
snoop/data/collections.py
snoop/data/indexing.py
snoop/data/views.py
snoop/defaultsettings.py

closes https://github.com/CRJI/EIC/issues/590

Configure refresh interval

---

snoop/data/digests.py

closes https://github.com/CRJI/EIC/issues/634

add size to child object

---

docs/filetypes.md
snoop/data/digests.py
snoop/data/management/commands/filestats.py
snoop/data/ocr.py

Add list of supported mime-types for OCR

---

snoop/data/analyzers/thumbnails.py
testsuite/test_thumbnail.py

retry thumbnail service after 404 error

---

Pipfile
Pipfile.lock
docs/mock-modules.txt
snoop/data/views.py

add ranged file response for download view

---

snoop/data/views.py

add accept range header

---

testsuite/conftest.py
testsuite/test_api.py
testsuite/test_pdf_preview.py

add tests for http ranges

---

snoop/data/views.py

fix content disposition header

---

snoop/data/analyzers/thumbnails.py

Thumbnail improvement

---

snoop/data/analyzers/entities.py
snoop/data/digests.py

closes CRJI/EIC#813
closes CRJI/EIC#844

Skip wrong ocr

---

snoop/data/tasks.py
testsuite/test_tags.py

tags test and correctly set bulk task broken status

---

snoop/data/management/commands/importtags.py
snoop/data/models.py
testsuite/test_tagimport.py

Import tags

---

.drone.yml
Dockerfile
Dockerfile.base

fix ci build

---

snoop/data/management/commands/checkdata.py

fix bug where an error would occur for empty collections.

fix checkdata command

---

testsuite/test_tagimport.py

add polling for second tag

---

snoop/data/digests.py

handle unknown encodings

---

Dockerfile.base

pin pypdf2 version in base image

---

Dockerfile
Dockerfile.base
snoop/data/analyzers/archives.py
snoop/defaultsettings.py

Archive speed / update 7zip

---

snoop/data/digests.py
testsuite/test_digest.py

closes https://github.com/CRJI/EIC/issues/1050

Capture all filenames and paths

---

docs/mock-modules.txt
runserver
snoop/common_data/models.py
snoop/common_data/urls.py
snoop/common_data/views.py
snoop/data/admin.py
snoop/data/collections.py
snoop/data/filesystem.py
snoop/data/management/commands/resetcollectionindex.py
snoop/data/management/commands/runworkers.py
snoop/data/models.py
snoop/data/s3.py
snoop/data/templates/snoop/admin_stats.html
snoop/defaultsettings.py

closes https://github.com/CRJI/EIC/issues/1014

Nextcloud collections
