snoop/data/analyzers/email.py
snoop/data/analyzers/emlx.py
snoop/data/filesystem.py
snoop/data/models.py
snoop/data/tasks.py
testsuite/conftest.py
testsuite/test_archives.py
testsuite/test_emails.py
testsuite/test_integration.py
testsuite/test_shaorma.py

A task gets the ability to say "hey, I need this task to run before I can finish my work". It aborts execution, gets marked with state "pending", and the new task gets added to its `depends_on` list.
I've used this mechanism to shaormify email html-to-text processing, conversion from msg to eml, and reconstructing an emlx from parts. Maybe this is a good way to allow emlx reconstruction to wait for dependent files to be imported as blobs.

Add missing dependency for a running task

---

requirements.in
requirements.txt
snoop/data/analyzers/html.py
snoop/data/digests.py
snoop/data/dispatcher.py
snoop/data/models.py
snoop/data/urls.py
snoop/data/views.py
testsuite/test_api.py
testsuite/test_emails.py

Three features rolled into a single PR:
* Clean HTML using the `bleach` library (fixes https://github.com/hoover/snoop2/issues/3)
* Provide a list of locations where a blob appears in the filesystem, check out https://github.com/hoover/ui/pull/17 for how it's used
* Count words in a document - the number is displayed in the search results
* If a file has a child directory, return its children

Locations, bleach, word count

---

snoop/data/analyzers/email.py
snoop/data/analyzers/pgp.py
snoop/data/digests.py
snoop/defaultsettings.py
testsuite/test_pgp.py

Unlike the original snoop implementation, this does not use python-gnupg, because it barfs when trying to import the keys in testdata. And it's so easy to call gpg directly.

PGP emails

---

snoop/data/analyzers/email.py
snoop/data/filesystem.py

The idea is to attempt conversion to eml and gracefully move on if it fails. Tested locally with a msg file, but I can't add it to testdata.

Some msg files are detected as `application/vnd.ms-outlook`

---

snoop/data/digests.py
testsuite/test_digest.py

For converted msg and emlx emails, the digest contains the hashes of the converted email, not the original. This makes it impossible to trace the original file across tools.
This patch changes digest to use the hashes, content-type and size from the original blob. The pk still comes from the converted message though; changing that will be more difficult.

Index original content-type, hashes and size

---

Dockerfile

See: https://github.com/celery/kombu/issues/841

fix(docker): Prevent using python 3.7 until kombu supports it

---

snoop/data/stats.py

The previous mapping seems to have a few mistakes that makes Kibana less useful.
* time filters do not work on non-indexed fields
* you could not do keyword aggregation on the 'func' field

Stats es mapping

---

snoop/data/digests.py

This improves faceting, i.e. to avoid this:

Lowercase the list of email domains

---

snoop/data/analyzers/tika.py

This should give us Keep-Alive connections for Tika calls, which could be a significant performance benefit:
http://docs.python-requests.org/en/master/user/advanced/#keep-alive

Try using a requests Session for Tika calls.

---

snoop/data/digests.py

Fixes https://github.com/CRJI/EIC/issues/110
Still needs some tests.

Skip the child dirs of container files when moving up the parent chain

---

snoop/data/management/commands/healthcheck.py

currently fails because trace.py binds on port 8000 on import,
which can not work with docker exec

wip: add health check for snoop

---

snoop/data/digests.py
snoop/data/indexing.py

Updated code to also index the path as text.
The reindex part seems to be doable from the snoop2 management commands.

Hoover - index path as text not only as keyword

---

snoop/data/analyzers/pgp.py
snoop/defaultsettings.py
testsuite/snoop-settings.py
testsuite/test_integration.py
testsuite/test_pgp.py

The PGP code was always kind of a hack, and it expects a gnupg home folder to be set up. So https://github.com/hoover/testdata/commit/c7c3bee47b431c43d4bbdfa1bae720e2dfd0e6d8 creates that folder in testdata, next to `data` and `ocr`. The idea is that, if you want pgp snooping, you set up the home folder in the collection folder, and snoop will auto-detect it.

Use `gpghome` folder which is already set up

---

snoop/defaultsettings.py

We could add some `sleep 100ms` instructions in between the auto-sync job retries to spread their runtime over a longer period, hopefully decreasing load.
Any ideas?

Decrease load impact from sync

---

snoop/data/tasks.py

The 'filesystem.walk' tasks are being retried, but the
OCR-related tasks are not.

retry ocr.walk_source tasks when sync=True

---

.drone.yml

CI fails when a dependabot branch with `/` in its name is pushed directly to docker hub: https://jenkins.liquiddemo.org/liquidinvestigations/hoover-snoop2/449

Replace slashes in branch name for docker hub

---

snoop/data/models.py
snoop/data/ocr.py
snoop/data/tasks.py

Rearrange some logging messages, fix `%r` of a `snoop.data.models.Task` being `''` in the current configuration, and add one `.iterator()` call where it should've been.

Log worker events

---

snoop/data/management/commands/initcollection.py
snoop/data/tasks.py
testsuite/docker-compose.override.travis-snoop2.yml

Snoop 0.5.0 broke the node testsuite (https://github.com/liquidinvestigations/node/commit/2f0b25aa98825417974d133bc362a913985bcda7). I suspect it's because workers start processing and push digests to the index before `initcollection` is called.

Automate index creation

---

snoop/data/admin.py
snoop/data/apps.py
snoop/data/auto_login.py
snoop/data/collections.py
snoop/data/templates/snoop/admin_index.html
snoop/data/templates/snoop/admin_index_default.html
snoop/defaultsettings.py
snoop/urls.py

Added auto-login and configurable url prefix for hosting behind a firewalled reverse proxy. Fixed the admin UI to show all info for all collections, implemented as one site per collection.

Urlprefix, admin sites

---

snoop/data/_file_types.py

closes CRJI/EIC#667.
Related to #425.
I mapped the missing filetypes. For `application/vnd.ms-office` and `application/CDFV2` I couldn't really find any information on what they actually are but they are mapped to `email` for now.
The only logic that is affected by the mapped type seems to be here:
https://github.com/liquidinvestigations/hoover-snoop2/blob/99b55e5c69a1bd522136effedb886f8d2bf667b8/snoop/data/digests.py#L445-L458
Do we want any changes there?

Map missing filetypes

---

snoop/data/analyzers/archives.py
snoop/data/collections.py
snoop/data/models.py
testsuite/test_archives.py

closes CRJI/EIC#670
There is still an issue, where the temporary directories are included in the created path.

refactor archive_walk using os.scandir

---

.drone.yml
snoop/data/tasks.py
snoop/defaultsettings.py

closes https://github.com/CRJI/EIC/issues/807
- adjusted dispatcher and task runner so it never queues more than some 40,000 tasks on a specific queue
- made adjustments to the dispatcher logic to lower proabability of double queueing
This does not remove the problem, since for outdated tasks we re-queue task types on separate dispatcher runs for each queue.

Fix double queueing

---

Dockerfile

fixes an issue where the container logs would show: 
`fatal: detected dubious ownership in repository at '/opt/hoover/snoop'`

fix repo ownership error

---

snoop/data/s3.py

fix error where snoop could not mount webdav directories that contain whitespace

quote url to handle whitespace
